// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.model;

import ar.com.ix.proyectos.model.Pais;

privileged aspect Pais_Roo_JavaBean {
    
    public String Pais.getNombre() {
        return this.nombre;
    }
    
    public void Pais.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
