// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.model;

import ar.com.ix.proyectos.model.Proyecto;

privileged aspect Proyecto_Roo_JavaBean {
    
    public String Proyecto.getCodigo() {
        return this.codigo;
    }
    
    public void Proyecto.setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
}
