// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.model;

import ar.com.ix.proyectos.model.Proyecto;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Proyecto_Roo_Configurable {
    
    declare @type: Proyecto: @Configurable;
    
}
