// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.web;

import ar.com.ix.proyectos.web.JornadaBean;
import java.io.Serializable;

privileged aspect JornadaBean_Roo_Serializable {
    
    declare parents: JornadaBean implements Serializable;
    
    private static final long JornadaBean.serialVersionUID = 1L;
    
}
