// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.web;

import ar.com.ix.proyectos.web.JornadaBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JornadaBean_Roo_Configurable {
    
    declare @type: JornadaBean: @Configurable;
    
}
