// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.web;

import ar.com.ix.proyectos.web.PaisBean;
import java.io.Serializable;

privileged aspect PaisBean_Roo_Serializable {
    
    declare parents: PaisBean implements Serializable;
    
    private static final long PaisBean.serialVersionUID = 1L;
    
}
