// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.web;

import ar.com.ix.proyectos.web.ProyectoBean;
import java.io.Serializable;

privileged aspect ProyectoBean_Roo_Serializable {
    
    declare parents: ProyectoBean implements Serializable;
    
    private static final long ProyectoBean.serialVersionUID = 1L;
    
}
