// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.web;

import ar.com.ix.proyectos.web.ProyectoBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProyectoBean_Roo_Configurable {
    
    declare @type: ProyectoBean: @Configurable;
    
}
