// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.web;

import ar.com.ix.proyectos.web.TecnicoBean;
import java.io.Serializable;

privileged aspect TecnicoBean_Roo_Serializable {
    
    declare parents: TecnicoBean implements Serializable;
    
    private static final long TecnicoBean.serialVersionUID = 1L;
    
}
