// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.proyectos.web.converter;

import ar.com.ix.proyectos.web.converter.AuditoriaVirtualConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AuditoriaVirtualConverter_Roo_Configurable {
    
    declare @type: AuditoriaVirtualConverter: @Configurable;
    
}
